# Generated by Django 5.1.3 on 2024-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postre',
            name='es_creado',
            field=models.BooleanField(default=False),
        ),
    ]
