# Generated by Django 5.1 on 2024-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
    ]
