# Generated by Django 5.1.3 on 2024-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoria_imagen_ingrediente_calorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='postre',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postre',
            name='es_recomendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='postres/'),
        ),
    ]
